### ISSUE TITLE
Mistake in "UX" workd conversion

### ISSUE THREAD

**Issue by ahmesaab** [tandrewnichols/indefinite#2]
a('UX Designer') returns **an UX Designer** and not **a UX Designer**

**Comment by tandrewnichols** [comment]
Yes, and lots of other words that start with long "u" sounds, like eulogy and unicorn. And some that start with silent consonants as well (like honor). I'm aware of this issue, but there's not really a way to solve that problem aside from maintaining a list of irregular words, which I'm not sure I'm keen to do. And acronyms like UX are a second tier of complication because they could be _anything_. I suppose at best, if all the letters of the first word are capitals (as is usually the case in an acronym), and the first letter is "U," I could return "a" instead of "an." But as whole, this issue isn't likely to be solved. English is just hard.

**Comment by tandrewnichols** [comment]
@ahmesaab I added acronym checking to v2.0.0. Give that a try.
